export enum GraphSyncStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
}

export enum GraphSyncAttemptStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
}

export enum GraphSyncEventType {
  MEDICINE_UPSERT = 'MEDICINE_UPSERT',
  MEDICINE_DEACTIVATE = 'MEDICINE_DEACTIVATE',
  MEDICINE_INGREDIENT_MAPPING_UPSERT = 'MEDICINE_INGREDIENT_MAPPING_UPSERT',
  ACTIVE_INGREDIENT_UPSERT = 'ACTIVE_INGREDIENT_UPSERT',
  ACTIVE_INGREDIENT_DEACTIVATE = 'ACTIVE_INGREDIENT_DEACTIVATE',
  DRUG_INTERACTION_RULE_UPSERT = 'DRUG_INTERACTION_RULE_UPSERT',
  DRUG_INTERACTION_RULE_DEACTIVATE = 'DRUG_INTERACTION_RULE_DEACTIVATE',
}

export interface GraphSyncEventPayload {
  entityType: string;
  entityId: string;
  eventType: GraphSyncEventType;
  sourceVersion: number;
  data?: any; // Additional contextual data if needed
}

export const MAX_GRAPH_SYNC_RETRIES = 3;
