// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node ./prisma/seed.ts",
  },
  datasource: {
    // CLI operations (like migrate) should use DIRECT_URL (Session Mode / port 5432)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
