import { Injectable, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateOrderDto } from './dto/create-order.dto';

@Injectable()
export class OrdersService {
  constructor(private prisma: PrismaService) {}

  async createOrder(createOrderDto: CreateOrderDto) {
    const { orderType, storeId, details } = createOrderDto;

    // Start a database transaction
    return this.prisma.$transaction(async (tx) => {
      let subtotal = 0;

      // 1. Verify inventory and calculate total
      for (const item of details) {
        const inventory = await tx.inventory.findFirst({
          where: {
            storeId: storeId,
            productVariantId: item.productVariantId,
          },
        });

        if (!inventory || inventory.quantity < item.quantity) {
          throw new BadRequestException(
            `Sản phẩm ID ${item.productVariantId} không đủ tồn kho.`
          );
        }

        subtotal += item.quantity * item.unitPrice;
      }

      // 2. Create the Order
      // In a real app, 'code' would be generated by a sequence or utility function.
      const orderCode = `POS-${Date.now()}`;
      
      const newOrder = await tx.order.create({
        data: {
          code: orderCode,
          storeId: storeId,
          orderType: orderType,
          status: 'COMPLETED', // POS orders are typically completed immediately
          subtotal: subtotal,
          totalAmount: subtotal, // Assuming no discounts/shipping for simple POS
          details: {
            create: details.map((item) => ({
              productVariantId: item.productVariantId,
              quantity: item.quantity,
              unitPrice: item.unitPrice,
              lineTotal: item.quantity * item.unitPrice,
            })),
          },
        },
        include: {
          details: true,
        },
      });

      // 3. Deduct inventory
      for (const item of details) {
        await tx.inventory.updateMany({
          where: {
            storeId: storeId,
            productVariantId: item.productVariantId,
          },
          data: {
            quantity: {
              decrement: item.quantity,
            },
          },
        });
      }

      return newOrder;
    });
  }
}
