name: Unit Test Check

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Backend)
        working-directory: ./backend
        run: npm ci

      - name: Generate Prisma Types
        working-directory: ./backend
        run: npm run prisma:generate

      - name: Run Unit Tests (Backend)
        working-directory: ./backend
        run: npm run test

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Frontend)
        working-directory: ./frontend
        run: npm ci

      - name: Run Unit Tests (Frontend)
        working-directory: ./frontend
        run: npm run test
